# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_lab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 543)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.vacuum_l = QtWidgets.QPushButton(Dialog)
        self.vacuum_l.setGeometry(QtCore.QRect(0, 140, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.vacuum_l.setFont(font)
        self.vacuum_l.setObjectName("vacuum_l")
        self.choose_lab = QtWidgets.QLabel(Dialog)
        self.choose_lab.setGeometry(QtCore.QRect(0, 0, 341, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.choose_lab.setFont(font)
        self.choose_lab.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.choose_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_lab.setObjectName("choose_lab")
        self.evaporation_l = QtWidgets.QPushButton(Dialog)
        self.evaporation_l.setGeometry(QtCore.QRect(0, 220, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.evaporation_l.setFont(font)
        self.evaporation_l.setObjectName("vaporization_l")
        self.sputtering_l = QtWidgets.QPushButton(Dialog)
        self.sputtering_l.setGeometry(QtCore.QRect(0, 300, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sputtering_l.setFont(font)
        self.sputtering_l.setObjectName("sputtering_l")
        self.magnetron_l = QtWidgets.QPushButton(Dialog)
        self.magnetron_l.setGeometry(QtCore.QRect(0, 380, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.magnetron_l.setFont(font)
        self.magnetron_l.setObjectName("magnetron_l")
        self.etching_l = QtWidgets.QPushButton(Dialog)
        self.etching_l.setGeometry(QtCore.QRect(0, 460, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.etching_l.setFont(font)
        self.etching_l.setObjectName("etching_l")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Load lab"))
        self.vacuum_l.setText(_translate("Dialog", "Vacuum"))
        self.choose_lab.setText(_translate("Dialog", "Choose lab"))
        self.evaporation_l.setText(_translate("Dialog", "Evaporation"))
        self.sputtering_l.setText(_translate("Dialog", "Sputtering"))
        self.magnetron_l.setText(_translate("Dialog", "Magnetron"))
        self.etching_l.setText(_translate("Dialog", "Etching"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
